/**
 * Deterministic Scoring Engine for Startup Intelligence
 *
 * PURPOSE
 * -------
 * Converts structured Research, Business and Red Team evidence
 * into a transparent 0-100 Venture Readiness Score.
 *
 * USER MODEL
 * ----------
 * 4 dimensions x 25 points = 100 total points.
 *
 * 1. Market Problem & Demand       /25
 * 2. Business Model & Economics    /25
 * 3. Defensibility & Moat          /25
 * 4. Execution & Risk              /25
 *
 * IMPORTANT
 * ---------
 * This engine does NOT make the final venture decision.
 *
 * ScoringEngine:
 *   Evidence -> Score
 *
 * scoringAndDecision:
 *   Score + Critical Evidence + Unknowns + Risks -> Decision
 *
 * orchestrationService:
 *   Controls execution order.
 *
 * CORE PRINCIPLES
 * ---------------
 * - Evidence over assumptions
 * - Unknown is not the same as positive evidence
 * - LLM must not directly control final scores
 * - No artificial score distribution
 * - No arbitrary competitor-count penalties
 * - Every meaningful deduction should be explainable
 * - Early-stage ventures should not be punished simply for lacking
 *   an already-established moat
 */

import {
  ResearchReport,
  BusinessReport,
  RedTeamReport,
  VentureScore
} from '../../types/domain';

export interface RawScoreInput {
  /**
   * Optional reasoning generated by an upstream agent.
   *
   * IMPORTANT:
   * These fields are explanatory only.
   *
   * The LLM does NOT provide the final numeric score.
   */
  marketReasoning?: string;
  businessReasoning?: string;
  moatReasoning?: string;
  riskReasoning?: string;
}

export class ScoringEngine {

  // ============================================================
  // Generic Helpers
  // ============================================================

  /**
   * Keep every dimension strictly between 0 and 25.
   */
  private static clamp(
    value: number,
    min = 0,
    max = 25
  ): number {
    return Math.max(
      min,
      Math.min(max, Math.round(value))
    );
  }

  /**
   * Count high-quality sources.
   *
   * This is intentionally conservative.
   *
   * PRIMARY / INDUSTRY_REPORT / HIGH credibility
   * are treated as stronger evidence than generic sources.
   */
  private static countVerifiedSources(
    research?: ResearchReport | null
  ): number {
    if (!research?.sources) {
      return 0;
    }

    return research.sources.filter(source =>
      source.reliabilityTier === 'PRIMARY' ||
      source.reliabilityTier === 'INDUSTRY_REPORT' ||
      source.credibility === 'HIGH'
    ).length;
  }

  /**
   * Count assumptions that still lack meaningful validation.
   */
  private static countUnvalidatedAssumptions(
    items: any[] = []
  ): number {
    return items.filter(item =>
      item.importance === 'CRITICAL' ||
      item.isHighRisk === true ||
      [
        'unverified',
        'UNVERIFIED',
        'unknown',
        'UNKNOWN',
        'unsupported',
        'UNSUPPORTED'
      ].includes(item.evidenceStatus)
    ).length;
  }

  /**
   * Normalize confidence values because reports may use
   * slightly different representations.
   */
  private static normalizeConfidence(
    confidence?: string
  ): 'HIGH' | 'MEDIUM' | 'LOW' | 'UNKNOWN' {
    if (!confidence) {
      return 'UNKNOWN';
    }

    const normalized = confidence.toUpperCase();

    if (normalized === 'HIGH') {
      return 'HIGH';
    }

    if (normalized === 'MEDIUM') {
      return 'MEDIUM';
    }

    if (normalized === 'LOW') {
      return 'LOW';
    }

    return 'UNKNOWN';
  }

  // ============================================================
  // 1. MARKET PROBLEM & DEMAND
  // Maximum: 25
  // ============================================================

  private static calculateMarketScore(
    research?: ResearchReport | null
  ): {
    score: number;
    deductions: string[];
    reasoning: string;
  } {

    /**
     * Start from a neutral position.
     *
     * 12/25 means:
     * "We currently have neither strong proof nor strong
     * evidence against the market opportunity."
     *
     * It is NOT a reward.
     */
    let score = 12;

    const deductions: string[] = [];

    if (!research) {
      score -= 3;

      deductions.push(
        '-3 pts: Research evidence is not available yet.'
      );

      return {
        score: this.clamp(score),
        deductions,
        reasoning:
          'Market opportunity cannot yet be strongly validated because research evidence is incomplete.'
      };
    }

    // ----------------------------------------------------------
    // Evidence Quality
    // ----------------------------------------------------------

    const verifiedSources =
      this.countVerifiedSources(research);

    const confidence = this.normalizeConfidence(
      research.confidenceScore ||
      research.confidence
    );

    if (
      confidence === 'HIGH' &&
      verifiedSources >= 3
    ) {
      score += 5;
    } else if (
      confidence === 'HIGH' ||
      verifiedSources >= 2
    ) {
      score += 3;
    } else if (
      confidence === 'MEDIUM'
    ) {
      score += 0;
    } else if (
      confidence === 'LOW'
    ) {
      score -= 2;

      deductions.push(
        '-2 pts: Market evidence currently has low confidence.'
      );
    } else {
      score -= 2;

      deductions.push(
        '-2 pts: Market evidence confidence could not be established.'
      );
    }

    // ----------------------------------------------------------
    // Market Tailwinds / Headwinds
    // ----------------------------------------------------------

    const tailwinds =
      research.tailwinds || [];

    const headwinds =
      research.headwinds || [];

    if (
      tailwinds.length > headwinds.length
    ) {
      score += 2;
    }

    if (
      headwinds.length > tailwinds.length
    ) {
      score -= 2;

      deductions.push(
        '-2 pts: Identified market headwinds outweigh tailwinds.'
      );
    }

    // ----------------------------------------------------------
    // Unvalidated Market Assumptions
    // ----------------------------------------------------------

    const unvalidated =
      research.unvalidatedAssumptions || [];

    if (unvalidated.length >= 3) {

      score -= 4;

      deductions.push(
        '-4 pts: Multiple critical market assumptions remain unvalidated.'
      );

    } else if (
      unvalidated.length > 0
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Important customer-demand assumptions remain unvalidated.'
      );
    }

    // ----------------------------------------------------------
    // Competitive Pressure
    //
    // IMPORTANT:
    // Number of competitors alone is NOT a negative signal.
    //
    // A large market can have many competitors and still be
    // attractive.
    //
    // We only penalize when research explicitly identifies
    // high competitive pressure.
    // ----------------------------------------------------------

    const competitors =
      research.competitors || [];

    const highThreatCompetitors =
      competitors.filter(
        (competitor: any) =>
          competitor.threatLevel === 'HIGH' ||
          competitor.competitiveThreat === 'HIGH'
      );

    if (
      highThreatCompetitors.length > 0
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Research identifies significant competitive pressure.'
      );
    }

    score = this.clamp(score);

    let reasoning: string;

    if (score >= 20) {
      reasoning =
        'Strong evidence of a meaningful market problem with credible demand signals and favorable market conditions.';
    } else if (score >= 15) {
      reasoning =
        'The market problem appears plausible and supported by some evidence, but important demand assumptions remain to be validated.';
    } else if (score >= 10) {
      reasoning =
        'The opportunity has some supporting evidence, but market demand remains materially uncertain.';
    } else {
      reasoning =
        'Market evidence is weak or contradicted by meaningful headwinds and unresolved demand assumptions.';
    }

    return {
      score,
      deductions,
      reasoning
    };
  }

  // ============================================================
  // 2. BUSINESS MODEL & ECONOMICS
  // Maximum: 25
  // ============================================================

  private static calculateBusinessScore(
    business?: BusinessReport | null
  ): {
    score: number;
    deductions: string[];
    reasoning: string;
  } {

    let score = 12;

    const deductions: string[] = [];

    if (!business) {

      score -= 3;

      deductions.push(
        '-3 pts: Business model evidence is not available yet.'
      );

      return {
        score: this.clamp(score),
        deductions,
        reasoning:
          'Commercial viability cannot yet be strongly assessed because business evidence is incomplete.'
      };
    }

    const commercialEconomics =
      business.businessModel?.commercialEconomics;

    const pricingPower =
      business.pricingPower ||
      commercialEconomics?.pricingPower;

    const capitalRequirement =
      business.capitalRequirement ||
      commercialEconomics?.capitalIntensity;

    const grossMargin =
      commercialEconomics?.estimatedGrossMargin;

    // ----------------------------------------------------------
    // Gross Margin
    // ----------------------------------------------------------

    if (
      grossMargin !== undefined &&
      typeof grossMargin === 'number'
    ) {

      if (grossMargin >= 80) {

        score += 5;

      } else if (grossMargin >= 65) {

        score += 3;

      } else if (grossMargin >= 50) {

        score += 1;

      } else if (grossMargin >= 30) {

        score -= 2;

        deductions.push(
          `-2 pts: Gross margin is relatively low at ${grossMargin}%.`
        );

      } else {

        score -= 5;

        deductions.push(
          `-5 pts: Gross margin below 30% (${grossMargin}%) creates significant economic pressure.`
        );
      }

    } else {

      score -= 2;

      deductions.push(
        '-2 pts: Gross margin evidence is unavailable.'
      );
    }

    // ----------------------------------------------------------
    // Pricing Power
    // ----------------------------------------------------------

    if (
      pricingPower === 'STRONG'
    ) {

      score += 3;

    } else if (
      pricingPower === 'WEAK'
    ) {

      score -= 3;

      deductions.push(
        '-3 pts: Weak pricing power creates commoditization and discounting risk.'
      );

    } else {

      score -= 1;

      deductions.push(
        '-1 pt: Pricing power has not yet been sufficiently validated.'
      );
    }

    // ----------------------------------------------------------
    // Capital Intensity
    // ----------------------------------------------------------

    if (
      capitalRequirement === 'HEAVY_CAPEX' ||
      capitalRequirement === 'WORKING_CAPITAL_INTENSIVE'
    ) {

      score -= 3;

      deductions.push(
        '-3 pts: High capital intensity increases financing and runway risk.'
      );

    } else if (
      capitalRequirement === 'CAPITAL_LIGHT'
    ) {

      score += 2;
    }

    // ----------------------------------------------------------
    // CAC Payback
    // ----------------------------------------------------------

    const paybackMonths =
      commercialEconomics?.paybackMonths;

    if (
      paybackMonths !== undefined &&
      typeof paybackMonths === 'number'
    ) {

      if (paybackMonths <= 6) {

        score += 2;

      } else if (paybackMonths <= 12) {

        score += 1;

      } else if (paybackMonths > 18) {

        score -= 3;

        deductions.push(
          `-3 pts: CAC payback exceeds 18 months (${paybackMonths} months).`
        );
      }
    }

    // ----------------------------------------------------------
    // Unvalidated Commercial Assumptions
    // ----------------------------------------------------------

    const assumptions =
      business.businessAssumptions ||
      business.assumptions ||
      [];

    const unvalidated =
      this.countUnvalidatedAssumptions(
        assumptions
      );

    if (
      unvalidated >= 3
    ) {

      score -= 4;

      deductions.push(
        '-4 pts: Multiple critical commercial assumptions remain unvalidated.'
      );

    } else if (
      unvalidated > 0
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Important commercial assumptions remain unvalidated.'
      );
    }

    score = this.clamp(score);

    let reasoning: string;

    if (score >= 20) {

      reasoning =
        'Strong commercial model with attractive economics, pricing potential, and relatively efficient capital requirements.';

    } else if (score >= 15) {

      reasoning =
        'Commercial model appears viable but important pricing, acquisition, or unit-economic assumptions still require validation.';

    } else if (score >= 10) {

      reasoning =
        'Commercial viability is plausible but currently constrained by economic uncertainty or unresolved assumptions.';

    } else {

      reasoning =
        'Business economics show significant weaknesses in margins, pricing power, capital intensity, or validation.';
    }

    return {
      score,
      deductions,
      reasoning
    };
  }

  // ============================================================
  // 3. DEFENSIBILITY & MOAT
  // Maximum: 25
  // ============================================================

  private static calculateMoatScore(
    business?: BusinessReport | null
  ): {
    score: number;
    deductions: string[];
    reasoning: string;
  } {

    let score = 12;

    const deductions: string[] = [];

    if (!business) {

      score -= 2;

      deductions.push(
        '-2 pts: Defensibility evidence is not available yet.'
      );

      return {
        score: this.clamp(score),
        deductions,
        reasoning:
          'Defensibility cannot yet be evaluated with sufficient evidence.'
      };
    }

    const moat =
      business.defensibilityMoat;

    const strength =
      moat?.strength;

    const moatType =
      moat?.type;

    // ----------------------------------------------------------
    // Moat Strength
    // ----------------------------------------------------------

    if (
      strength === 'STRONG'
    ) {

      score += 6;

    } else if (
      strength === 'FRAGILE'
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Current defensibility appears fragile.'
      );

    } else if (
      strength === 'NONE'
    ) {

      score -= 5;

      deductions.push(
        '-5 pts: No meaningful current defensibility has been identified.'
      );

    } else {

      score -= 1;

      deductions.push(
        '-1 pt: Defensibility evidence is still inconclusive.'
      );
    }

    // ----------------------------------------------------------
    // Structural Moat Mechanisms
    // ----------------------------------------------------------

    if (
      moatType === 'HIGH_SWITCHING_COST' ||
      moatType === 'NETWORK_EFFECTS' ||
      moatType === 'DATA_LOCKIN'
    ) {

      score += 3;
    }

    // ----------------------------------------------------------
    // Commodity Exposure
    // ----------------------------------------------------------

    if (
      moatType === 'NONE'
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Product currently has significant exposure to commodity competition.'
      );
    }

    score = this.clamp(score);

    let reasoning: string;

    if (score >= 20) {

      reasoning =
        'The venture shows evidence of structural defensibility such as switching costs, network effects, proprietary data, or another durable advantage.';

    } else if (score >= 15) {

      reasoning =
        'The venture has some differentiation, but the durability of that advantage remains uncertain.';

    } else if (score >= 10) {

      reasoning =
        'The venture currently has limited defensibility and may depend heavily on execution and product development.';

    } else {

      reasoning =
        'The venture currently appears highly exposed to imitation or commodity competition.';
    }

    return {
      score,
      deductions,
      reasoning
    };
  }

  // ============================================================
  // 4. EXECUTION & ADVERSARIAL RISK
  // Maximum: 25
  // ============================================================

  private static calculateExecutionScore(
    redTeam?: RedTeamReport | null
  ): {
    score: number;
    deductions: string[];
    reasoning: string;
  } {

    /**
     * Start from neutral.
     *
     * We intentionally DO NOT start from 23/25.
     *
     * Missing Red Team evidence must not automatically mean
     * excellent execution.
     */
    let score = 15;

    const deductions: string[] = [];

    if (!redTeam) {

      score -= 3;

      deductions.push(
        '-3 pts: Red Team evidence is not available yet.'
      );

      return {
        score: this.clamp(score),
        deductions,
        reasoning:
          'Execution and risk profile cannot yet be confidently assessed because adversarial analysis is incomplete.'
      };
    }

    // ----------------------------------------------------------
    // Risks
    // ----------------------------------------------------------

    const risks =
      redTeam.criticalRisks ||
      redTeam.fatalFlaws ||
      [];

    const lethalFlaws =
      risks.filter(
        (risk: any) =>
          risk.severity === 'LETHAL' ||
          risk.severity === 'CRITICAL'
      );

    const highFlaws =
      risks.filter(
        (risk: any) =>
          risk.severity === 'HIGH'
      );

    const mediumFlaws =
      risks.filter(
        (risk: any) =>
          risk.severity === 'MEDIUM'
      );

    // ----------------------------------------------------------
    // Critical / Lethal Risks
    // ----------------------------------------------------------

    if (
      lethalFlaws.length > 0
    ) {

      const deduct =
        Math.min(
          10,
          lethalFlaws.length * 5
        );

      score -= deduct;

      deductions.push(
        `-${deduct} pts: ${lethalFlaws.length} critical failure risk(s) identified by Red Team.`
      );
    }

    // ----------------------------------------------------------
    // High Risks
    // ----------------------------------------------------------

    if (
      highFlaws.length > 0
    ) {

      const deduct =
        Math.min(
          6,
          highFlaws.length * 2
        );

      score -= deduct;

      deductions.push(
        `-${deduct} pts: ${highFlaws.length} high-severity execution risk(s) identified.`
      );
    }

    // ----------------------------------------------------------
    // Medium Risks
    // ----------------------------------------------------------

    if (
      mediumFlaws.length >= 3
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Multiple medium-severity execution risks remain.'
      );
    }

    // ----------------------------------------------------------
    // Contradictions
    // ----------------------------------------------------------

    const contradictions =
      redTeam.contradictions ||
      [];

    if (
      contradictions.length > 0
    ) {

      const deduct =
        Math.min(
          5,
          contradictions.length
        );

      score -= deduct;

      deductions.push(
        `-${deduct} pts: Evidence contradictions remain unresolved.`
      );
    }

    // ----------------------------------------------------------
    // Failure Conditions
    // ----------------------------------------------------------

    const failureConditions =
      redTeam.failureConditions ||
      [];

    if (
      failureConditions.length >= 3
    ) {

      score -= 2;

      deductions.push(
        '-2 pts: Multiple credible failure conditions have been identified.'
      );
    }

    score = this.clamp(score);

    let reasoning: string;

    if (score >= 20) {

      reasoning =
        'The venture shows a relatively resilient execution profile with limited critical risks and no major unresolved failure mechanism.';

    } else if (score >= 15) {

      reasoning =
        'Execution appears manageable, but the venture still requires controlled validation of important operational and GTM risks.';

    } else if (score >= 10) {

      reasoning =
        'Several meaningful execution or market risks remain and should be tested before major investment.';

    } else {

      reasoning =
        'The Red Team identified severe vulnerabilities that materially threaten execution or venture viability.';
    }

    return {
      score,
      deductions,
      reasoning
    };
  }

  // ============================================================
  // MAIN CALCULATION
  // ============================================================

  public static calculate(
    ventureId: string,
    raw?: Partial<RawScoreInput>,
    research?: ResearchReport | null,
    business?: BusinessReport | null,
    redTeam?: RedTeamReport | null
  ): VentureScore {

    // ----------------------------------------------------------
    // Calculate all four dimensions
    // ----------------------------------------------------------

    const market =
      this.calculateMarketScore(
        research
      );

    const businessResult =
      this.calculateBusinessScore(
        business
      );

    const moat =
      this.calculateMoatScore(
        business
      );

    const execution =
      this.calculateExecutionScore(
        redTeam
      );

    // ----------------------------------------------------------
    // Total
    // ----------------------------------------------------------

    const totalScore =
      market.score +
      businessResult.score +
      moat.score +
      execution.score;

    // ----------------------------------------------------------
    // Recommendation Tier
    //
    // NOTE:
    // This is a SCORE TIER only.
    //
    // The actual BUILD / VALIDATE FIRST / REDESIGN /
    // DO NOT PURSUE decision belongs to scoringAndDecision.
    // ----------------------------------------------------------

    let recommendationTier:
      VentureScore['recommendationTier'] =
      'MODERATE_READINESS';

    if (
      totalScore >= 80
    ) {

      recommendationTier =
        'HIGH_READINESS';

    } else if (
      totalScore >= 60
    ) {

      recommendationTier =
        'MODERATE_READINESS';

    } else if (
      totalScore >= 40
    ) {

      recommendationTier =
        'HIGH_VULNERABILITY';

    } else {

      recommendationTier =
        'CRITICALLY_FLAWED';
    }

    // ----------------------------------------------------------
    // Final VentureScore
    // ----------------------------------------------------------

    return {

      id:
        `scr_${Date.now()}`,

      ventureId,

      calculatedAt:
        new Date().toISOString(),

      totalScore,

      dimensions: {

        marketProblemUrgency: {

          score:
            market.score,

          reasoning:
            raw?.marketReasoning ||
            market.reasoning,

          deductions:
            market.deductions
        },

        businessModelViability: {

          score:
            businessResult.score,

          reasoning:
            raw?.businessReasoning ||
            businessResult.reasoning,

          deductions:
            businessResult.deductions
        },

        defensibilityMoat: {

          score:
            moat.score,

          reasoning:
            raw?.moatReasoning ||
            moat.reasoning,

          deductions:
            moat.deductions
        },

        executionRisk: {

          score:
            execution.score,

          reasoning:
            raw?.riskReasoning ||
            execution.reasoning,

          deductions:
            execution.deductions
        }
      },

      recommendationTier
    };
  }
}
